### ISSUE TITLE
Spell check skips words in strings

### ISSUE THREAD

**Issue by vdumitraskovic** [kmszk/CCSpellCheck.vim#1]
Words in strings are skipped by the plugin.

For example, propTypes are marked as good, but the 'propTypes' are marked as bad.

**Comment by kamykn** [comment]
Hi, @smesko85.

I'm trying to find out this problem, but same problem does not occur with my Vim (or NeoVim).
Can you tell me your situation when the problem occurred.

1.  Which are you using? Vim / NeoVim

2. Please tell me the situation in details so that I can investigate; (e.g. Your source code or screenshot.)

3. Does the problem occur with a specific words?

**Comment by vdumitraskovic** [comment]
Hi, @kamykn .
Thank you for responding! 
1. I'm using NeoVim
2. It is happening to me with almost every string. I don't see any particular reason why it is happening. I'm attaching the screenshot from one of the projects with filetype 'javascript.jsx'.
![screen shot 2018-09-10 at 9 06 08 am](https://user-images.githubusercontent.com/6537892/45281683-d1c3b600-b4d8-11e8-9e2f-13718cf92df3.png)
3. Unfortunately not. It seems that it happens with all of the words inside the strings.

**Comment by kamykn** [comment]
@smesko85
OK.
I confirmed that there are problems with my plugin.
Please wait for a while until I fix it.
Thank you for your reporting!!

**Comment by kamykn** [comment]
@smesko85 
I fixed the bug you reported.
Could you please check if it is fixed in newer versions?

**Comment by vdumitraskovic** [comment]
@kamykn Hi, it works! It looks like the default config `let g:CCSpellCheckEnable` is now `0`. But I've set it to `1` in my config, and it works like a charm.

Thank You!
